name: schedule job

on:
  schedule:    # Spelling correct ki
    - cron: "0 0 * * *"   # Midnight daily (UTC)

jobs: 
  run-script: 
    runs-on: ubuntu-latest   # Indentation theek ki

    steps:
      - name: print message
        run: echo "execute hogya g"
